### ISSUE TITLE
Is there any chance to add more node_label and edge_label?

### ISSUE THREAD

**Issue by lihaohaode** [jajupmochi/graphkit-learn#3]
Hi, lin. In the file 'graphfiles.py' you used the 'loadDataset' function to read the dataset and build graphs. I found that all the functions corresponding to different datasets like 'loadCT'   , 'loadGXL ' , 'loadSDF' etc. usually add one node lable 'atom' and one edge label 'bond_type'. Is there any chance to add more node_label and edge_label to make the classification more accurate？
Thanks, man.

**Comment by jajupmochi** [comment]
Sorry for the delay. Please check function [`load_dataset`](https://github.com/jajupmochi/graphkit-learn/blob/master/gklearn/utils/graph_files.py#L6). Let me know if there is any problem, please. Thanks.
